---
title: "plot evolutionary trajectory for multiple models"
author: "Andrea Chen"
date: "`r Sys.Date()`"
output: pdf_document
---

# parameter for plotting
```{r setup, include=FALSE}
wd_path <- normalizePath(dirname(rstudioapi::getActiveDocumentContext()$path))
setwd(wd_path)
base_plot_folder <- "../plots/2_13/constant_env/"
if (!dir.exists(base_plot_folder)) {
  dir.create(base_plot_folder, recursive = TRUE)
}
hcl_color_palette <- "Dark 2" # color pattern for lines 
```

# load evolutionary trajectory data
```{r}
allele_df <- readRDS("../r_data/constant_env/allele.rds")
summary_stat_df <- readRDS("../r_data/constant_env/data_summary.rds")
```

```{r}
allele_df$delta_p_percent <- allele_df$frequencies - ave(frequencies, list(reg, n, psi, shift_size, rep, id), FUN = function(x) {
  # get freq at t_before and t_after
  t_before <- 10000
  t_after <- 10015
  freq_before <- x[which.min(abs(allele_df$gen[allele_df$frequencies == x] - t_before))]
  freq_after <- x[which.min(abs(allele_df$gen[allele_df$frequencies == x] - t_after))]
  freq_after - freq_before
})
```

## the 99th percentile of absolute effect sizes over time
```{r}
# Keep segregating mutations only (typical for most architecture stats)
seg <- allele_df$frequencies > 0 & allele_df$frequencies < 1 & !allele_df$isFixed
df  <- allele_df[seg, ]

# Convenience
a <- df$effect_size
p <- df$frequencies

# Per-mutation additive-variance contribution v_i = 2p(1-p)a^2
v <- 2 * p * (1 - p) * (a^2)

```

```{r pressure, echo=FALSE}
# Grouping key: include whatever metadata columns you want
key <- interaction(df$reg, df$n, df$psi, df$shift_size, df$rep, df$gen, drop = TRUE, sep="_")

mean_abs <- aggregate(abs(a), list(key = key), mean)
q90_abs  <- aggregate(abs(a), list(key = key), function(x) unname(quantile(x, 0.90, na.rm=TRUE)))
q99_abs  <- aggregate(abs(a), list(key = key), function(x) unname(quantile(x, 0.99, na.rm=TRUE)))

# Tail probability above a threshold tau (choose tau meaningful in your scale)
tau <- 0.1
tail_p <- aggregate(abs(a) > tau, list(key = key), mean)

```

```{r}
split_key <- do.call(rbind, strsplit(as.character(mean_abs$key), split="\\_"))  # interaction uses "."
colnames(split_key) <- c("reg","n","psi","shift_size","rep","gen")

tail_stats <- data.frame(
  reg = split_key[,1],
  n = as.integer(split_key[,2]),
  psi = as.numeric(split_key[,3]),
  shift_size = as.integer(split_key[,4]),
  rep = as.integer(split_key[,5]),
  gen = as.integer(split_key[,6]),
  mean_abs = mean_abs$x,
  q90_abs = q90_abs$x,
  q99_abs = q99_abs$x,
  tail_p_tau = tail_p$x
)



```

```{r}
# cond <- with(tail_stats, reg=="fit" & n==10 & shift_size==120 & psi==0.9)
# d <- tail_stats[cond, ]
# d <- d[order(d$gen), ]

# ---- create output folder if needed ----
out_dir <- file.path(base_plot_folder, "allele_q99")
if (!dir.exists(out_dir)) {
  dir.create(out_dir, recursive = TRUE)
}

for (reg_i in c("ave", "fit", "ext")) {
  for (n_i in c(2, 5, 8, 20)) {
    for (psi_i in c(0.0, 0.5, 0.9)) {
      for (shift_size_i in c(20, 40, 60)) {
        cond <- with(tail_stats, reg==reg_i & n==n_i & shift_size==shift_size_i & psi==psi_i)
        d <- tail_stats[cond, ]
        d <- d[order(d$gen), ]
        # ---- build filename dynamically ----
        out_file <- file.path(
          out_dir,
          paste0("allele_effect_size_q99_reg_", reg_i, "_n_", n_i, "_shift_", shift_size_i, "_psi_", psi_i, ".png")
        )
        png(filename = out_file, width = 800, height = 600)
        plot(NA, NA, xlim = range(d$gen), ylim = range(d$q99_abs), xlab = "Generation", ylab = "99th Percentile of |Effect Size|", main = paste( "n:", n_i, "Shift:", shift_size_i, "Psi:", psi_i))
        for (rep_i in unique(d$rep)) {
          d_rep <- d[d$rep == rep_i, ]
          lines(d_rep$gen, d_rep$q99_abs)
        }
        box()
        dev.off()
      }
    }
  }
}
```


## effective number of mutations contributing to additive variance (L_eff)
```{r}
Va <- aggregate(v, list(key = key), sum)
sum_v  <- Va$x
sum_v2 <- aggregate(v^2, list(key = key), sum)$x
Leff   <- (sum_v^2) / sum_v2

arch_basic <- data.frame(key = Va$key, Va = sum_v, Leff = Leff)

```

```{r}
# Split indices by group
idx_list <- split(seq_len(nrow(df)), key)

topk_frac <- function(idx, k) {
  vv <- v[idx]
  s <- sum(vv)
  if (!is.finite(s) || s <= 0) return(NA_real_)
  # partial sort: for small k, sorting is fine; if huge, consider sort.int with partial
  frac <- sum(sort(vv, decreasing = TRUE)[seq_len(min(k, length(vv)))]) / s
  frac
}

frac_top1  <- vapply(idx_list, topk_frac, numeric(1), k = 1)
frac_top5  <- vapply(idx_list, topk_frac, numeric(1), k = 5)
frac_top20 <- vapply(idx_list, topk_frac, numeric(1), k = 20)

arch_topk <- data.frame(
  key = names(idx_list),
  frac_top1 = as.numeric(frac_top1),
  frac_top5 = as.numeric(frac_top5),
  frac_top20 = as.numeric(frac_top20)
)

arch <- merge(arch_basic, arch_topk, by="key", all.x=TRUE)

```

```{r}
split_key <- do.call(rbind, strsplit(as.character(arch$key), split="\\_")) 
colnames(split_key) <- c("reg","n","psi","shift_size","rep","gen")
arch <- cbind(
  data.frame(
    reg=split_key[,1],
    n=as.integer(split_key[,2]),
    psi=as.numeric(split_key[,3]),
    shift_size=as.integer(split_key[,4]),
    rep=as.integer(split_key[,5]),
    gen=as.integer(split_key[,6])
  ),
  arch[, c("Va","Leff","frac_top1","frac_top5","frac_top20")]
)

```

```{r}
# ---- create output folder if needed ----
out_dir <- file.path(base_plot_folder, "Leff")
if (!dir.exists(out_dir)) {
  dir.create(out_dir, recursive = TRUE)
}
col <- hcl.colors(3, palette = hcl_color_palette)
for (reg_i in c("ave", "fit", "ext")) {
  for (n_i in c(2, 5, 8, 20)) {
    for (psi_i in c(0.0, 0.5, 0.9)) {
      for (shift_size_i in c(20, 40, 60)) {
        cond0 <- with(arch, reg==reg_i & n==n_i & shift_size==shift_size_i & psi==psi_i)
        # cond5 <- with(arch, reg==reg_i & n==n_i & shift_size==shift_size_i & psi==0.5)
        # cond9 <- with(arch, reg==reg_i & n==n_i & shift_size==shift_size_i & psi==0.9)

        d0 <- arch[cond0, ][order(arch[cond0,"gen"]), ]
        d5 <- arch[cond5, ][order(arch[cond5,"gen"]), ]
        d9 <- arch[cond9, ][order(arch[cond9,"gen"]), ]

        # ---- build filename dynamically ----
        out_file <- file.path(
          out_dir,
          paste0("leff_reg_", reg_i, "_n_", n_i, "_shift_", shift_size_i, "_psi_", psi_i, ".png")
        )
        png(filename = out_file, width = 800, height = 600)
        plot(NA, NA, xlim = range(d0$gen), ylim = range(d0$Leff), xlab = "Generation", ylab = "L_eff", main = paste( "n:", n_i, "Shift:", shift_size_i, "Psi:", psi_i))
        for (rep_i in unique(d0$rep)) {
          if (psi_i == 0.5) {
            d5_rep <- d5[d5$rep == rep_i, ]
            lines(d5_rep$gen, d5_rep$Leff, col = col[2])
          }
          if (psi_i == 0.9) {
            d9_rep <- d9[d9$rep == rep_i, ]
            lines(d9_rep$gen, d9_rep$Leff, col = col[3])
          }
          if (psi_i == 0.0) {
             d0_rep <- d0[d0$rep == rep_i, ]
             lines(d0_rep$gen, d0_rep$Leff, col = col[1])
          }
        }
        # legend("topright", legend=c("psi=0", "psi=0.5", "psi=0.9"), col=col, lty=1)
        box()
        dev.off()
      }
    }
  }
}

```

## 

```{r}
# first seen and last seen per allele within each condition (include metadata!)
key_id <- interaction(df$reg, df$n, df$psi, df$shift_size, df$rep, df$id, drop=TRUE, sep="_")

first_seen <- aggregate(df$gen, list(key_id=key_id), min)
last_seen  <- aggregate(df$gen, list(key_id=key_id), max)
max_freq   <- aggregate(df$frequencies, list(key_id=key_id), max)
mean_abs_a <- aggregate(abs(df$effect_size), list(key_id=key_id), mean)
origin_min <- aggregate(df$originTick, list(key_id=key_id), min)

life <- data.frame(
  key_id = first_seen$key_id,
  first_seen = first_seen$x,
  last_seen  = last_seen$x,
  lifespan   = last_seen$x - first_seen$x + 1,
  max_freq   = max_freq$x,
  mean_abs_a = mean_abs_a$x,
  originTick = origin_min$x
)

# Parse key_id back
split_key <- do.call(rbind, strsplit(as.character(life$key_id), split="\\_")) 
colnames(split_key) <- c("reg","n","psi","shift_size","rep","id")
life <- cbind(
  data.frame(
    reg=split_key[,1],
    n=as.integer(split_key[,2]),
    psi=as.numeric(split_key[,3]),
    shift_size=as.integer(split_key[,4]),
    rep=as.integer(split_key[,5]),
    id=split_key[,6]
  ),
  life[, c("originTick","first_seen","last_seen","lifespan","max_freq","mean_abs_a")]
)

```

```{r}
# ---- create output folder if needed ----
out_dir <- file.path(base_plot_folder, "lifespan_vs_effect")
if (!dir.exists(out_dir)) {
  dir.create(out_dir, recursive = TRUE)
}
col <- hcl.colors(3, palette = hcl_color_palette)
for (reg_i in c("ave", "fit", "ext")) {
  for (n_i in c(2, 5, 8, 20)) {
    for (psi_i in c(0.0, 0.5, 0.9)) {
      for (shift_size_i in c(20, 40, 60)) {
        cond0 <- with(life, reg==reg_i & n==n_i & shift_size==shift_size_i & psi==psi_i)
        d <- life[cond0, ]

        # ---- build filename dynamically ----
        out_file <- file.path(
          out_dir,
          paste0("reg_", reg_i, "_n_", n_i, "_shift_", shift_size_i, "_psi_", psi_i, ".png")
        )
        png(filename = out_file, width = 800, height = 600)
        plot(NA, NA, xlim = range(d$mean_abs_a), ylim = range(d$lifespan), xlab = "mean |effect| of allele", ylab = "lifespan (gens)", main = paste( "n:", n_i, "Shift:", shift_size_i, "Psi:", psi_i))
        for (rep_i in unique(d$rep)) {
          d_rep <- d[d$rep == rep_i, ]
          col_rep <- if (psi_i == 0.5) {
            col[2]
          } else if (psi_i == 0.9) {
            col[3]
          } else {
            col[1]
          }
          points(d_rep$mean_abs_a, d_rep$lifespan, col = col_rep)
        }
        # legend("topright", legend=c("psi=0", "psi=0.5", "psi=0.9"), col=col, lty=1)
        box()
        dev.off()
      }
    }
  }
}


```

## frequency vs effect_size
```{r}
# ---- create output folder if needed ----
out_dir <- file.path(base_plot_folder, "frequency_vs_effect")
if (!dir.exists(out_dir)) {
  dir.create(out_dir, recursive = TRUE)
}
col <- hcl.colors(3, palette = hcl_color_palette)
breaks <- seq(-3, 3, by=0.1)

avg_allele_df <- aggregate(frequencies ~ gen + reg + n + psi + shift_size,
                    data = allele_df,
                    FUN = mean,
                    na.rm = TRUE)

for (reg_i in c("ave")) {
  for (n_i in c(2)) {
    for (psi_i in c(0.0)) {
      for (shift_size_i in c(20)) {
        cond0 <- with(avg_allele_df, reg==reg_i & n==n_i & shift_size==shift_size_i & psi==psi_i)
        d <- avg_allele_df[cond0, ]

        d$eff_bin <- cut(d$frequencies, breaks = breaks, include.lowest = TRUE, right = FALSE)

        tab <- tapply(d$frequencies, list(d$gen, d$eff_bin), sum, na.rm = TRUE)
        ord <- order(tab$gen)
        tab <- tab[ord, , drop = FALSE]

        zmat <- t(tab)

        # # ---- build filename dynamically ----
        # out_file <- file.path(
        #   out_dir,
        #   paste0("reg_", reg_i, "_n_", n_i, "_shift_", shift_size_i, "_psi_", psi_i, ".png")
        # )
        # png(filename = out_file, width = 800, height = 600)
        # plot(NA, NA, xlim = range(d$mean_abs_a), ylim = range(d$lifespan), xlab = "mean |effect| of allele", ylab = "lifespan (gens)", main = paste( "n:", n_i, "Shift:", shift_size_i, "Psi:", psi_i))
        # for (rep_i in unique(d$rep)) {
        #   d_rep <- d[d$rep == rep_i, ]
        #   col_rep <- if (psi_i == 0.5) {
        #     col[2]
        #   } else if (psi_i == 0.9) {
        #     col[3]
        #   } else {
        #     col[1]
        #   }
        #   points(d_rep$mean_abs_a, d_rep$lifespan, col = col_rep)
        # }
        # # legend("topright", legend=c("psi=0", "psi=0.5", "psi=0.9"), col=col, lty=1)
        # box()
        # dev.off()
      }
    }
  }
}


```



## pdf of the heatmaps 
```{r}
# ----------------- user-editable settings -----------------
ns   <- c(2, 5, 8, 20)
psis <- c(0, 0.5, 0.9)
regs <- c("ave", "fit", "ext")
szs  <- c(20, 40, 60)
rep_to_plot <- 2   # choose which replicate

xcol <- "gen"  # change if your allele df uses "generation"

# choose y axis definition and z-value
y_mode <- "signed"     # "signed" or "abs"
z_mode <- "mean_freq"       # "prop" or "count" or "density"

# effect size bin breaks:
# signed bins around 0 OR abs bins starting at 0
if (y_mode == "signed") {
  # choose a fixed range; adjust to your effect distribution
  eff_lim <- 3.0
  breaks_vec <- seq(-eff_lim, eff_lim, length.out = 101)  # 100 bins
} else {
  eff_lim <- 1.0
  breaks_vec <- seq(0, eff_lim, length.out = 101)
}

# optional: focus on new mutations only
new_only <- FALSE
new_window <- 0  # 0 => originTick==gen; 10 => last 10 gens

plot_folder <- file.path(base_plot_folder, "allele_frequency_heatmap_pdf_byrep")
if (!dir.exists(plot_folder)) dir.create(plot_folder, recursive = TRUE)

# ==========================================================
for (shift_size in szs) {

  pdf_file <- file.path(
    plot_folder,
    paste0("sz_", shift_size,
           "_y_", y_mode, "_z_", z_mode,
           if (new_only) paste0("_new_w", new_window) else "",
           "_rep_", rep_to_plot,
           ".pdf")
  )

  pdf(pdf_file, width = 18, height = 10, onefile = TRUE)

  for (reg_i in regs) {
    # ---- build all heatmats for this page + shared zlim ----
    hm_list <- vector("list", length(psis) * length(ns))
    dim(hm_list) <- c(length(psis), length(ns))  # treat as 2D
    max_vals <- c()

    for (ip in seq_along(psis)) {
      p <- psis[ip]
      for (in_ in seq_along(ns)) {
        n <- ns[in_]

        filt <- list(
          reg = reg_i,
          psi = p,
          n = n,
          shift_size = shift_size,
          rep = rep_to_plot
        )

        hm <- .build_effect_heatmat(
          df = allele_df,
          filter = filt,
          xcol = xcol,
          breaks_vec = breaks_vec,
          y = y_mode,
          z = z_mode,
          only_segregating = TRUE,
          new_only = new_only,
          new_window = new_window
        )

        hm_list[[ip, in_]] <- hm
        if (!is.null(hm)) max_vals <- c(max_vals, max(hm$mat, na.rm = TRUE))
      }
    }


    zlim_page <- c(0, max(max_vals, na.rm = TRUE))
    if (!is.finite(zlim_page[2]) || zlim_page[2] <= 0) zlim_page <- c(0, 1e-6)

    # ---- layout: 3 rows × (4 panels + 1 colorbar) ----
    lay <- matrix(1:12, nrow = 3, ncol = 4, byrow = TRUE)
    lay <- cbind(lay, 13)
    layout(lay, widths = c(rep(1, 4), 0.40))

    par(oma = c(0.5, 0.5, 2.0, 0.5))
    par(
      mar = c(2.8, 3.0, 2.0, 0.5),
      mgp = c(1.8, 0.6, 0),
      cex.axis = 0.9,
      cex.lab  = 1.0,
      cex.main = 0.95
    )

    # ---- draw panels row-major: psi rows, n columns ----
    idx <- 1
    for (p in psis) {
      for (n in ns) {

        hm <- hm_list[[idx]]

        panel_title <- paste0("n=", n, ", psi=", p)
        xlab <- if (p == psis[length(psis)]) "Generation" else ""
        ylab <- if (n == ns[1]) {
          if (y_mode == "abs") "|effect_size|" else "effect_size"
        } else ""

        .plot_allele_heat_panel(
          hm = hm,
          zlim = zlim_page,
          col = hcl.colors(10, palette = hcl_color_palette),
          main = panel_title,
          xlab = xlab,
          ylab = ylab,
          axes = TRUE,
          box = TRUE
        )

        idx <- idx + 1
      }
    }

    # ---- colorbar cell ----
    par(mar = c(2.8, 0.3, 2.0, 3.5), mgp = c(1.8, 0.6, 0))
    .draw_colorbar_panel(zlim_page,
                         col = hcl.colors(10, palette = hcl_color_palette),
                         label = if (z_mode == "prop") "Proportion" else if (z_mode == "count") "Count" else "Density")

    # ---- page title ----
    mtext(
      paste0("shift_size=", shift_size,
             " | reg=", reg_i,
             " | y=", y_mode,
             " | z=", z_mode,
             if (new_only) paste0(" | new_only(w=", new_window, ")") else ""),
      side = 3, outer = TRUE, line = 0.2, cex = 1.2
    )
  }

  dev.off()
  cat("Wrote:", pdf_file, "\n")
}


```

```{r}
# ----------------- user-editable settings -----------------
ns   <- c(2, 5, 8, 20)
psis <- c(0, 0.5, 0.9)
regs <- c("ave", "fit", "ext")
szs  <- c(20, 40, 60)

t_before <- 10000
t_after  <- 10015
xcol <- "gen"   # change to "generation" if needed

out_dir <- file.path(base_plot_folder, "delta_p_scatter_pdf")
if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
# =========================================================

for (shift_size in szs) {

  pdf_file <- file.path(
    out_dir,
    paste0("delta_p_effect_scatter_sz_", shift_size,
           "_t", t_before, "_to_", t_after, ".pdf")
  )

  pdf(pdf_file, width = 18, height = 10, onefile = TRUE)

  for (reg_i in regs) {

    # ---- build panel data first + shared limits ----
    panel_data <- vector("list", length(psis) * length(ns))
    idx_fun <- function(ip, in_) (ip - 1L) * length(ns) + in_

    all_x <- c()
    all_y <- c()

    for (ip in seq_along(psis)) {
      p <- psis[ip]
      for (in_ in seq_along(ns)) {
        n <- ns[in_]

        filt <- list(reg = reg_i, psi = p, n = n, shift_size = shift_size)

        m <- .delta_p_panel_data(
          df = allele_df,
          filter = filt,
          t_before = t_before,
          t_after = t_after,
          xcol = xcol
        )

        idx <- idx_fun(ip, in_)
        panel_data[[idx]] <- m  # m can be NULL; that's fine in a list
        # print(idx)
        # print(length(m))
        # print(length(panel_data))

        if (!is.null(m) && nrow(m)) {
          all_x <- c(all_x, m$effect)
          all_y <- c(all_y, m$delta_p)
        }
      }
    }

    # shared axis ranges per page
    xlim_page <- range(all_x, na.rm = TRUE)
    ylim_page <- range(all_y, na.rm = TRUE)
    if (!is.finite(xlim_page[1])) xlim_page <- c(-1, 1)
    if (!is.finite(ylim_page[1])) ylim_page <- c(-0.1, 0.1)

    # add a little padding
    pad <- function(r, f=0.04) {
      w <- diff(r); if (!is.finite(w) || w==0) w <- 1
      c(r[1] - f*w, r[2] + f*w)
    }
    xlim_page <- pad(xlim_page)
    ylim_page <- pad(ylim_page)

    # ---- layout: 3 rows × (4 panels + 1 legend cell) ----
    lay <- matrix(1:12, nrow = 3, ncol = 4, byrow = TRUE)
    lay <- cbind(lay, 13)
    layout(lay, widths = c(rep(1, 4), 0.55))

    par(oma = c(0.5, 0.5, 2.0, 0.5))
    par(
      mar = c(2.8, 3.0, 2.0, 0.5),
      mgp = c(1.8, 0.6, 0),
      cex.axis = 0.9,
      cex.lab  = 1.0,
      cex.main = 0.95
    )

    # ---- draw panels row-major: psi rows, n cols ----
    reps_all <- sort(unique(allele_df$rep))
    rep_cols <- hcl.colors(max(1, length(reps_all)), palette = hcl_color_palette)

    for (ip in seq_along(psis)) {
      p <- psis[ip]
      for (in_ in seq_along(ns)) {
        n <- ns[in_]
        idx <- idx_fun(ip, in_)
        m <- panel_data[[idx]]


        panel_title <- paste0("n=", n, ", psi=", p)
        xlab <- if (ip == length(psis)) "effect_size" else ""
        ylab <- if (in_ == 1) expression(Delta*p) else ""

        plot(NA, xlim = xlim_page, ylim = ylim_page,
             xlab = xlab, ylab = ylab, main = panel_title)

        abline(h = 0, v = 0, lty = 3)

        # ... after plot() + abline(h=0,v=0)

        if (!is.null(m) && nrow(m)) {
          # points (your existing code)
          rep_idx <- match(m$rep, reps_all)
          points(m$effect, m$delta_p, pch = 16, cex = 0.35, col = rep_cols[rep_idx])

          # fit line on pooled data in this panel
          info <- .fit_line_info(m$effect, m$delta_p)

          # add fitted line
          if (is.finite(info$b1) && is.finite(info$b0)) {
            abline(a = info$b0, b = info$b1, lwd = 2)
          }

          # panel legend with slope/intercept (plus N)
          leg_txt <- sprintf("Δp = %.3g + %.3g·a\nN=%d", info$b0, info$b1, nrow(m))
          legend("topleft", legend = leg_txt, bty = "n", cex = 0.85)
        } else {
          text(mean(xlim_page), mean(ylim_page), "no data", cex = 0.8)
        }

        box()
      }
    }

    # ---- legend cell (right column) ----
    par(mar = c(2.8, 0.3, 2.0, 0.3))
    plot.new()
    title(main = "Replicate", line = -1)
    if (length(reps_all)) {
      legend("center", legend = reps_all, pch = 16, col = rep_cols, bty = "n", cex = 0.9)
    }

    # ---- page title ----
    mtext(
      paste0("shift_size=", shift_size,
             " | reg=", reg_i,
             " | Δp = p(", t_after, ") - p(", t_before, ")"),
      side = 3, outer = TRUE, line = 0.2, cex = 1.2
    )
  }

  dev.off()
  cat("Wrote:", pdf_file, "\n")
}

```


```{r}
# ----------------- user-editable settings -----------------
ns   <- c(2, 5, 8, 20)
psis <- c(0, 0.5, 0.9)
regs <- c("ave", "fit", "ext")
szs  <- c(20, 40, 60)

t_before <- 10000
t_after  <- 10015
xcol <- "gen"         # change to "generation" if needed

Kmax <- 200           # how far the top-K curve extends

out_dir <- file.path(base_plot_folder, "top_contrib_pdf")
if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
# =========================================================

for (shift_size in szs) {

  pdf_file <- file.path(
    out_dir,
    paste0("top_contrib_sz_", shift_size, "_t", t_before, "_to_", t_after, "_Kmax_", Kmax, ".pdf")
  )

  pdf(pdf_file, width = 18, height = 10, onefile = TRUE)

  for (reg_i in regs) {

    # ---- build all panels first (so we can share y-limits if you want) ----
    n_ns <- length(ns); n_ps <- length(psis)
    panel_obj <- vector("list", n_ps * n_ns)

    max_y <- 0

    for (ip in seq_along(psis)) {
      p <- psis[ip]
      for (in_ in seq_along(ns)) {
        n <- ns[in_]

        filt <- list(reg = reg_i, psi = p, n = n, shift_size = shift_size)

        m <- .delta_p_panel_data_union(
          df = allele_df, filter = filt,
          t_before = t_before, t_after = t_after, xcol = xcol
        )

        obj <- .top_contrib_curves(m, Kmax = Kmax)

        idx <- (ip - 1L) * n_ns + in_
        panel_obj[[idx]] <- obj

        # y is always between 0 and 1, but keep this in case you change metric
        if (!is.null(obj)) max_y <- max(max_y, 1, na.rm=TRUE)
      }
    }

    # ---- layout: 3 rows × (4 panels + 1 legend cell) ----
    lay <- matrix(1:12, nrow = 3, ncol = 4, byrow = TRUE)
    lay <- cbind(lay, 13)
    layout(lay, widths = c(rep(1, 4), 0.60))

    par(oma = c(0.5, 0.5, 2.0, 0.5))
    par(
      mar = c(2.8, 3.0, 2.0, 0.5),
      mgp = c(1.8, 0.6, 0),
      cex.axis = 0.9,
      cex.lab  = 1.0,
      cex.main = 0.95
    )

    # ---- draw panels ----
    for (ip in seq_along(psis)) {
      p <- psis[ip]
      for (in_ in seq_along(ns)) {
        n <- ns[in_]
        idx <- (ip - 1L) * n_ns + in_
        obj <- panel_obj[[idx]]

        panel_title <- paste0("n=", n, ", psi=", p)
        xlab <- if (ip == length(psis)) "Top K alleles (ranked by |2aΔp|)" else ""
        ylab <- if (in_ == 1) "Cumulative fraction of total |Δz| explained" else ""

        plot(NA, xlim = c(1, Kmax), ylim = c(0, 1),
             xlab = xlab, ylab = ylab, main = panel_title)

        if (is.null(obj)) {
          text(Kmax*0.5, 0.5, "no data", cex=0.9)
          box()
          next
        }

        K <- obj$K
        curves <- obj$curves

        # thin replicate curves
        for (i in seq_len(nrow(curves))) {
          yy <- curves[i, ]
          if (all(!is.finite(yy))) next
          lines(K, yy, lwd = 1)
        }

        # thick mean curve across reps
        mean_curve <- apply(curves, 2, function(x) mean(x, na.rm=TRUE))
        lines(K, mean_curve, lwd = 3)

        # annotate Top1/Top5/Top20 (mean across reps)
        ts <- obj$top_stats
        top1  <- mean(ts[, "top1"],  na.rm=TRUE)
        top5  <- mean(ts[, "top5"],  na.rm=TRUE)
        top20 <- mean(ts[, "top20"], na.rm=TRUE)

        leg_txt <- sprintf("mean Top1=%.3f\nmean Top5=%.3f\nmean Top20=%.3f\nreps=%d",
                           top1, top5, top20, nrow(curves))
        legend("bottomright", legend = leg_txt, bty = "n", cex = 0.85)

        box()
      }
    }

    # ---- legend cell (right column) ----
    par(mar = c(2.8, 0.3, 2.0, 0.3))
    plot.new()
    text(0, 0.8, "How to read:", adj = 0)
    text(0, 0.65, "y(K) = fraction of total |Δz|", adj = 0)
    text(0, 0.55, "explained by top K alleles", adj = 0)
    text(0, 0.40, "thin lines = reps", adj = 0)
    text(0, 0.30, "thick line = mean across reps", adj = 0)
    text(0, 0.15, "Δz_i ≈ 2 a_i Δp_i", adj = 0)

    # ---- page title ----
    mtext(
      paste0("Top-contributor curves | shift_size=", shift_size,
             " | reg=", reg_i,
             " | t=", t_before, "→", t_after),
      side = 3, outer = TRUE, line = 0.2, cex = 1.2
    )
  }

  dev.off()
  cat("Wrote:", pdf_file, "\n")
}

```

# delta p as a percentage of p before
```{r}
# ----------------- user-editable settings -----------------
ns   <- c(2, 5, 8, 20)
psis <- c(0, 0.5, 0.9)
regs <- c("ave", "fit", "ext")
szs  <- c(20, 40, 60)

t_before <- 10000
t_after  <- 10015
xcol <- "gen"   # change to "generation" if needed

out_dir <- file.path(base_plot_folder, "delta_p_scatter_high_p")
if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
# =========================================================

for (shift_size in szs) {

  pdf_file <- file.path(
    out_dir,
    paste0("delta_p_scatter_sz_", shift_size,
           "_t", t_before, "_to_", t_after, ".pdf")
  )

  pdf(pdf_file, width = 18, height = 10, onefile = TRUE)

  for (reg_i in regs) {

    # ---- build panel data first + shared limits ----
    panel_data <- vector("list", length(psis) * length(ns))
    idx_fun <- function(ip, in_) (ip - 1L) * length(ns) + in_

    all_x <- c()
    all_y <- c()

    for (ip in seq_along(psis)) {
      p <- psis[ip]
      for (in_ in seq_along(ns)) {
        n <- ns[in_]

        filt <- list(reg = reg_i, psi = p, n = n, shift_size = shift_size)

        m <- .delta_p_panel_data(
          df = allele_df,
          filter = filt,
          t_before = t_before,
          t_after = t_after,
          xcol = xcol
        )
        #filter to high p before only
        m <- m[m$p0 >= 0.5, ]

        idx <- idx_fun(ip, in_)
        panel_data[[idx]] <- m  # m can be NULL; that's fine in a list

        if (!is.null(m) && nrow(m)) {
          all_x <- c(all_x, m$effect)
          all_y <- c(all_y, m$delta_p)
        }
      }
    }

    # shared axis ranges per page
    xlim_page <- range(all_x, na.rm = TRUE)
    ylim_page <- range(all_y, na.rm = TRUE)
    if (!is.finite(xlim_page[1])) xlim_page <- c(-1, 1)
    if (!is.finite(ylim_page[1])) ylim_page <- c(-0.1, 0.1)

    # add a little padding
    pad <- function(r, f=0.04) {
      w <- diff(r); if (!is.finite(w) || w==0) w <- 1
      c(r[1] - f*w, r[2] + f*w)
    }
    xlim_page <- pad(xlim_page)
    ylim_page <- pad(ylim_page)

    # ---- layout: 3 rows × (4 panels + 1 legend cell) ----
    lay <- matrix(1:12, nrow = 3, ncol = 4, byrow = TRUE)
    lay <- cbind(lay, 13)
    layout(lay, widths = c(rep(1, 4), 0.55))

    par(oma = c(0.5, 0.5, 2.0, 0.5))
    par(
      mar = c(2.8, 3.0, 2.0, 0.5),
      mgp = c(1.8, 0.6, 0),
      cex.axis = 0.9,
      cex.lab  = 1.0,
      cex.main = 0.95
    )

    # ---- draw panels row-major: psi rows, n cols ----
    reps_all <- sort(unique(allele_df$rep))
    rep_cols <- hcl.colors(max(1, length(reps_all)), palette = hcl_color_palette)

    for (ip in seq_along(psis)) {
      p <- psis[ip]
      for (in_ in seq_along(ns)) {
        n <- ns[in_]
        idx <- idx_fun(ip, in_)
        m <- panel_data[[idx]]


        panel_title <- paste0("n=", n, ", psi=", p)
        xlab <- if (ip == length(psis)) "effect_size" else ""
        ylab <- if (in_ == 1) expression(Delta*p*"(%)") else ""

        plot(NA, xlim = xlim_page, ylim = ylim_page,
             xlab = xlab, ylab = ylab, main = panel_title)

        abline(h = 0, v = 0, lty = 3)

        # ... after plot() + abline(h=0,v=0)

        if (!is.null(m) && nrow(m)) {
          # points (your existing code)
          rep_idx <- match(m$rep, reps_all)
          points(m$effect, m$delta_p, pch = 16, cex = 0.35, col = rep_cols[rep_idx])

          # fit line on pooled data in this panel
          info <- .fit_line_info(m$effect, m$delta_p)

          # add fitted line
          if (is.finite(info$b1) && is.finite(info$b0)) {
            abline(a = info$b0, b = info$b1, lwd = 2)
          }

          # panel legend with slope/intercept (plus N)
          leg_txt <- sprintf("delta p = %.3g + %.3g·a\nN=%d", info$b0, info$b1, nrow(m))
          legend("topleft", legend = leg_txt, bty = "n", cex = 0.85)
        } else {
          text(mean(xlim_page), mean(ylim_page), "no data", cex = 0.8)
        }

        box()
      }
    }

    # ---- legend cell (right column) ----
    par(mar = c(2.8, 0.3, 2.0, 0.3))
    plot.new()
    title(main = "Replicate", line = -1)
    if (length(reps_all)) {
      legend("center", legend = reps_all, pch = 16, col = rep_cols, bty = "n", cex = 0.9)
    }

    # ---- page title ----
    mtext(
      paste0("shift_size=", shift_size,
             " | reg=", reg_i,
             " | Δp = p(", t_after, ") - p(", t_before, ")"),
      side = 3, outer = TRUE, line = 0.2, cex = 1.2
    )
  }

  dev.off()
  cat("Wrote:", pdf_file, "\n")
}

```

