---
title: "plot evolutionary trajectory for multiple models"
author: "Andrea Chen"
date: "`r Sys.Date()`"
output: pdf_document
---

# parameter for plotting
```{r setup, include=FALSE}
wd_path <- normalizePath(dirname(rstudioapi::getActiveDocumentContext()$path))
setwd(wd_path)
base_plot_folder <- "plots"
plot_psi <- c(0.0, 0.1, 0.3, 0.5, 0.7, 0.9, 1.0) # all psi values to plot for fittest model
plot_beta <- c(0.0, 0.01, 0.03, 0.05, 0.07, 0.3, 0.5, 0.7, 0.9, 1.0) # all beta values to plot for inverse-variance model
plot_n <- c(2, 8, 20, 50) # group sizes to plot for both models
plot_shift_sizes <- c(40,80,120) # shift sizes to plot for both models
regimes <- c("inv", "fit", "ext", "ave")  # "inv" = inverse variance model, "fit" = fittest individual model
plot_reps <- TRUE  # whether to plot individual replicate series 
plot_exp_fit <- TRUE  # whether to fit and plot exponential decay curve to evolutionary trajectory plot
hcl_color_palette <- "Dark 2" # color pattern for lines 
tick_seq <- 9999:10100 # ticks to plot
```

# load evolutionary trajectory data
```{r}
data_df <- readRDS("data_summary.rds")
# data_df <- readRDS("var_ext.rds")
```

# PARAMETER: if you want to plot for FITTEST model, change parameters here
```{r}
# plot_psi <- c(0.0, 0.5)
plot_psi <- c(0.0, 0.5, 0.9)
plot_beta <- c(0.0, 0.01, 0.03, 0.05, 0.07)
plot_n <- c(2, 8, 20, 50)
plot_shift_sizes <- c(40)
regimes <- regimes <- c("fit", "ext", "ave")
plot_exp_fit <- FALSE
plot_reps <- TRUE
tick_seq <- 9999:10100 # ticks to plot
plot_summary_multi_by_beta_ticks(data_df,
                                out_subfolder = "trajectory_partial_reps",
                                regimes = regimes)
```

# PARAMETER: if you want to plot for INVERSE_VARIANCE model, change parameters here
```{r}
plot_beta <- c(0.0, 0.3)
plot_n <- c(8)
plot_shift_sizes <- c(120)
regimes <- c("inv")
plot_exp_fit <- FALSE # i recommend FALSE because inverse-variance model does not fit exponential decay well
```

# RUN PLOTTING
```{r}
regimes <- c("inv")
plot_beta <- c(0.0, 0.01, 0.03, 0.05, 0.07)
tick_seq <- 10100:10400 # ticks to plot
plot_exp_fit <- FALSE
plot_reps <- FALSE
plot_summary_multi_by_beta_ticks(data_df,
                                out_subfolder = "trajectory_full_ext",
                                regimes = regimes)
```

