---
title: "plot evolutionary trajectory for multiple models"
author: "Andrea Chen"
date: "`r Sys.Date()`"
output: pdf_document
---

# parameter for plotting
```{r setup, include=FALSE}
wd_path <- normalizePath(dirname(rstudioapi::getActiveDocumentContext()$path))
setwd(wd_path)
base_plot_folder <- "../plots/11_17/e_psi_from_constant_to_variation/"
plot_n <- c(2, 8, 20, 50) # group sizes to plot for both models
plot_shift_sizes <- c(40,80,120) # shift sizes to plot for both models
regimes <- c("inv", "fit", "ext", "ave")  # "inv" = inverse variance model, "fit" = fittest individual model
plot_reps <- TRUE  # whether to plot individual replicate series 
hcl_color_palette <- "Dark 2" # color pattern for lines 
tick_seq <- 9970:10300 # ticks to plot
```

# load evolutionary trajectory data
```{r}
data_df <- readRDS("../r_data/dsicrete_evolve_sociality/summary.rds")
```

```{r}
data_df <- summary_stat_df
```

```{r}
reg = "ave"          # choose from "inv", "fit", "ext", "ave"
n = 50               # choose from 2, 8, 20, 50
shift_size = 120     # choose from 40, 80, 120
plot_folder = paste0(base_plot_folder, "psi_mean/")
colname = "psi_mean"  # column to plot
if (!dir.exists(plot_folder)) {
  dir.create(plot_folder, recursive = TRUE)
}

for (n in c(2,8,20,50)){
    for (reg in c("inv", "fit", "ext", "ave")){
        filt_A <- list(reg = reg, n = n, start_psi = 0.2)
        filt_B <- list(reg = reg, n = n, start_psi = 0.5)
        filt_C <- list(reg = reg, n = n, start_psi = 0.8)

        title <- paste0(
        if (reg == "inv") "Homogenous group" else
            if (reg == "fit") "copy the best" else
            if (reg == "ext") "copy the extreme" else
                if (reg == "ave") "copy the average",
        " model (n = ", n, ")"
        )

        png(paste0(plot_folder, "reg_", reg, "_n_", n, ".png"), width = 2200, height = 1800, res = 150)
        par(cex.axis = 1.6, cex.lab = 2.0, cex.main = 1.0, mar = c(4.5, 6, 3, 1))

        plot_lines_multi(
            df      = data_df,
            filters = list(filt_A, filt_B, filt_C),
            ycol    = colname,  # << choose the column to plot
            labels  = list(
                title = title,
                x = "Tick",
                y = "Proportion"      # or any y label you want
            ),
            show_rep = TRUE,       # faded per-rep lines? TRUE/FALSE
            cols = c(
                hcl.colors(3, hcl_color_palette, rev = TRUE)[1],
                hcl.colors(3, hcl_color_palette, rev = TRUE)[2],
                hcl.colors(3, hcl_color_palette, rev = TRUE)[3]
            ),
            ylim = c(0, 0.5),
            xlim = c(10000, 10300)
        )

        leg_expr <- as.expression(lapply(c(filt_A$start_psi, filt_B$start_psi, filt_C$start_psi),
                                        function(v) bquote(psi == .(v))))
        legend("topright", bty = "n", legend = leg_expr,
            col = c(
                hcl.colors(3, hcl_color_palette, rev = TRUE)[1],
                hcl.colors(3, hcl_color_palette, rev = TRUE)[2],
                hcl.colors(3, hcl_color_palette, rev = TRUE)[3]
            ),
            lwd = 3, cex = 2.2)
        dev.off()

    }
}
```

```{r}

```