---
title: "analysis for 1 trait model"
author: "Andrea Chen"
date: "`r Sys.Date()`"
output: pdf_document
---

## 30 generation

```{r}
load_data <- function(path){
  # Get all matching files
  files <- list.files(path = path, pattern = "^psi11_.*_c_.*_[1-5]\\.tsv$", full.names = TRUE)
  
  # Initialize list to store data by y
  data_by_qtl <- list()
  
  for (file in files) {
    # Parse filename
    fname <- basename(file)
    parts <- strsplit(gsub("psi11_|\\.tsv", "", fname), "_c_")[[1]]
    psi11_val <- as.numeric(parts[1])
    qtl_and_i <- strsplit(parts[2], "_")[[1]]
    qtl_count <- as.integer(qtl_and_i[1])
    
    # Read file
    df <- read.table(file, header = TRUE, sep = "\t")
    
    # Add psi11 and qtl_count columns
    df$psi11 <- psi11_val
    df$qtl_count <- qtl_count
    
    # Store in list grouped by qtl_count
    qtl_key <- as.character(qtl_count)
    if (!is.null(data_by_qtl[[qtl_key]])) {
      data_by_qtl[[qtl_key]] <- rbind(data_by_qtl[[qtl_key]], df)
    } else {
      data_by_qtl[[qtl_key]] <- df
    }
  }
  return(data_by_qtl)
}
```

```{r plot_allele_frequency}
plot_pf_trajectories <- function(df_group, pf_prefix = "pf_", transparency = 0.1, ylim = c(0.45, 0.65)) {
  pf_cols <- grep(pf_prefix, names(df_group), value = TRUE)
  psi_vals <- sort(unique(df_group$psi11))
  color_palette <- rainbow(length(psi_vals))

  # Adjust plot margins and allow drawing outside
  old_par <- par(no.readonly = TRUE)
  on.exit(par(old_par))
  par(mar = c(5, 4, 4, 8))  # Extra space on the right

  plot(NULL, xlim = range(df_group$cycle), ylim = ylim,
       xlab = "Cycle", ylab = "Allele frequency",
       main = paste("Allele Frequency Trajectories (QTL =", unique(df_group$qtl_count), ")"))

  for (i in seq_along(psi_vals)) {
    psi <- psi_vals[i]
    sub_df <- df_group[df_group$psi11 == psi, ]

    # Generate trial ID (assumes equal-length replicates)
    cycles_per_trial <- length(unique(sub_df$cycle))
    sub_df$trial_id <- rep(1:(nrow(sub_df) / cycles_per_trial), each = cycles_per_trial)

    for (pf_col in pf_cols) {
      # Split by trial
      trial_list <- split(sub_df[, c("cycle", pf_col)], sub_df$trial_id)

      # OPTIONAL: plot individual trial lines (transparent)
      # for (trial in trial_list) {
      #   lines(trial$cycle, trial[[pf_col]],
      #         col = adjustcolor(color_palette[i], alpha.f = transparency), lwd = 1)
      # }

      # Compute mean over trials
      pf_mat <- do.call(cbind, lapply(trial_list, function(x) x[[pf_col]]))
      if (is.vector(pf_mat)) {
        pf_mat <- matrix(pf_mat, ncol = 1)
      }
      pf_mean <- rowMeans(pf_mat, na.rm = TRUE)
      lines(unique(sub_df$cycle), pf_mean, col = adjustcolor(color_palette[i], alpha.f = 1), lwd = 2)
    }
  }

  legend("topright", inset = c(-0.3, 0), xpd = TRUE,
         legend = paste("psi11 =", psi_vals),
         col = color_palette, lwd = 2, bty = "n")
}


```

```{r}
data_by_qtl<-load_data("../tsv_output")
```


```{r}
for (data in data_by_qtl){
  plot_pf_trajectories(data, transparency=0.5)
}

```

```{r}
plot_avg_pf_across_loci <- function(df_group, pf_prefix = "pf_", transparency = 0.2) {
  pf_cols <- grep(pf_prefix, names(df_group), value = TRUE)
  psi_vals <- sort(unique(df_group$psi11))
  color_palette <- rainbow(length(psi_vals))

  # Save original plot settings and adjust right margin
  old_par <- par(no.readonly = TRUE)
  on.exit(par(old_par))
  par(mar = c(5, 4, 4, 8))  # Add space for legend

  plot(NULL, xlim = range(df_group$cycle), ylim = c(0.45, 0.6),
       xlab = "Cycle", ylab = "Mean allele frequency (across loci)",
       main = paste("Average Allele Frequency Trajectories (QTL =", unique(df_group$qtl_count), ")"))

  for (i in seq_along(psi_vals)) {
    psi <- psi_vals[i]
    sub_df <- df_group[df_group$psi11 == psi, ]

    # Generate trial ID (assumes equal-length replicates)
    cycles_per_trial <- length(unique(sub_df$cycle))
    sub_df$trial_id <- rep(1:(nrow(sub_df) / cycles_per_trial), each = cycles_per_trial)

    # Compute per-trial average across loci at each cycle
    trial_list <- split(sub_df, sub_df$trial_id)
    trial_means <- lapply(trial_list, function(trial) {
      data.frame(
        cycle = trial$cycle,
        mean_pf = rowMeans(trial[, pf_cols], na.rm = TRUE)
      )
    })

    # Plot individual trials (transparent)
    for (trial_df in trial_means) {
      lines(trial_df$cycle, trial_df$mean_pf,
            col = adjustcolor(color_palette[i], alpha.f = transparency), lwd = 1)
    }

    # Compute mean over trials
    mean_matrix <- do.call(cbind, lapply(trial_means, function(x) x$mean_pf))
    mean_over_trials <- rowMeans(mean_matrix, na.rm = TRUE)

    # Plot bold mean line
    lines(trial_means[[1]]$cycle, mean_over_trials, col = color_palette[i], lwd = 2)
  }

  legend("topright", inset = c(-0.3, 0), xpd = TRUE,
         legend = paste("psi11 =", psi_vals),
         col = color_palette, lwd = 2, bty = "n")
}


```

```{r}
for (data in data_by_qtl){
  plot_avg_pf_across_loci(data, transparency=0.1)
}
```

```{r}
plot_trait_over_time <- function(df_group, column, transparency = 0.2) {
  if (!column %in% names(df_group)) {
    stop(paste("Column", column, "not found in data"))
  }

  psi_vals <- sort(unique(df_group$psi11))
  color_palette <- rainbow(length(psi_vals))

  # Save current plot settings and expand right margin
  old_par <- par(no.readonly = TRUE)
  on.exit(par(old_par))  # Ensure original settings restored on exit
  par(mar = c(5, 4, 4, 8))  # Extend right margin for legend

  plot(NULL, xlim = range(df_group$cycle), ylim = range(df_group[[column]], na.rm = TRUE),
       xlab = "Cycle", ylab = column,
       main = paste(column, "Trajectory (QTL =", unique(df_group$qtl_count), ")"))

  for (i in seq_along(psi_vals)) {
    psi <- psi_vals[i]
    sub_df <- df_group[df_group$psi11 == psi, ]

    # Determine number of cycles per trial
    cycles_per_trial <- length(unique(sub_df$cycle))
    n_trials <- nrow(sub_df) / cycles_per_trial

    if (n_trials != floor(n_trials)) {
      stop("Data doesn't divide evenly into trials. Check if trials are complete or ordered correctly.")
    }

    sub_df$trial_id <- rep(1:n_trials, each = cycles_per_trial)

    trial_list <- split(sub_df, sub_df$trial_id)

    for (trial in trial_list) {
      lines(trial$cycle, trial[[column]],
            col = adjustcolor(color_palette[i], alpha.f = transparency), lwd = 1)
    }

    trait_matrix <- sapply(trial_list, function(df) df[[column]])
    if (is.vector(trait_matrix)) {
      trait_matrix <- matrix(trait_matrix, ncol = 1)
    }

    trait_mean <- rowMeans(trait_matrix, na.rm = TRUE)
    lines(trial_list[[1]]$cycle, trait_mean, col = color_palette[i], lwd = 2)
  }

  legend("topright", inset = c(-0.3, 0), xpd = TRUE,
         legend = paste("psi11 =", psi_vals),
         col = color_palette, lwd = 2, bty = "n")
}

```

```{r}
for (data in data_by_qtl){
  plot_trait_over_time(data, "z1_mean")
}
```

```{r}
for (data in data_by_qtl){
  plot_trait_over_time(data, "z1_sd")
}
```

```{r}
for (data in data_by_qtl){
  plot_trait_over_time(data, "a1_mean")
}
```

```{r}
for (data in data_by_qtl){
  plot_trait_over_time(data, "a1_sd")
}
```

## 50 generation

```{r}
data_50gen <-load_data("../tsv_output/50gen")
```

```{r}
for (data in data_50gen){
  df_pos <- subset(data, psi11 >= 0)
  plot_pf_trajectories(df_pos, transparency=0.5, ylim=c(0.45, 0.7))
}

```

```{r}
for (data in data_50gen){
  df_pos <- subset(data, psi11 <= 0)
  plot_pf_trajectories(df_pos, transparency=0.5, ylim=c(0.45, 0.7))
}

```

```{r}
for (data in data_50gen){
  df_pos <- subset(data, psi11 >= 0)
  plot_avg_pf_across_loci(df_pos, transparency=0.1)
}
```

```{r}
for (data in data_50gen){
  df_pos <- subset(data, psi11 <= 0)
  plot_avg_pf_across_loci(df_pos, transparency=0.1)
}
```

```{r}
for (data in data_50gen){
  df_pos <- subset(data, psi11 >= 0)
  plot_trait_over_time(df_pos, "z1_mean")
}
```
```{r}
for (data in data_50gen){
  df_pos <- subset(data, psi11 <= 0)
  plot_trait_over_time(df_pos, "z1_mean")
}
```


```{r}
for (data in data_50gen){
  plot_trait_over_time(data, "z1_sd")
}
```

```{r}
for (data in data_50gen){
  df_pos <- subset(data, psi11 >= 0)
  plot_trait_over_time(df_pos, "a1_sd")
}
```
```{r}
for (data in data_50gen){
  df_pos <- subset(data, psi11 <= 0)
  plot_trait_over_time(df_pos, "a1_sd")
}
```

```{r}
for (data in data_50gen){
  df_pos <- subset(data, psi11 >= 0)
  plot_trait_over_time(df_pos, "a1_mean")
}
```

```{r}
for (data in data_50gen){
  df_pos <- subset(data, psi11 <= 0)
  plot_trait_over_time(df_pos, "a1_mean")
}
```

```{r}
for (data in data_50gen){
  df_pos <- subset(data, psi11 <= 0)
  plot_trait_over_time(df_pos, "fitness_sd")
}
```
```{r}
for (data in data_50gen){
  df_pos <- subset(data, psi11 >= 0)
  plot_trait_over_time(df_pos, "fitness_sd")
}
```

```{r}
sample = data_50gen$`10`
df_selected <- subset(sample, psi11 %in% c(0.0, 0.6, -0.6))
plot_trait_over_time(df_selected, "z1_mean")
```


## optimum = -8
```{r}
data_opt_n8 <-load_data("../tsv_output/opt-8")
```

```{r}
for (data in data_opt_n8){
  df_pos <- subset(data, psi11 >= 0)
  plot_trait_over_time(df_pos, "z1_mean")
}
```


```{r}
for (data in data_opt_n8){
  df_pos <- subset(data, psi11 <= 0)
  plot_trait_over_time(df_pos, "z1_mean")
}
```

```{r}
sample = data_opt_n8$`10`
df_selected <- subset(sample, psi11 %in% c(0.0, 0.6, -0.6))
plot_trait_over_time(df_selected, "z1_mean")
```




